version: '3.8'

services:
  api:
    build:
      context: ./
    container_name: fastapi-app
    command: uvicorn app.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
