repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: debug-statements
    -   id: detect-private-key
    -   id: name-tests-test
        args: ["--pytest-test-first"]
    -   id: pretty-format-json
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
        language_version: python3
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args: ["--application-directories", "app:tests"]
-   repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
    -   id: gitleaks
